apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2   # Número de Pods que quieres correr
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: yaeth/devops-practica/flask-app:latest   # Cambia esto por tu imagen subida
        ports:
        - containerPort: 5000

